site_name: ClarkePark
site_description: Transformación de Clarke y Park
copyright: Creado por Marco Polo Jácome Toss
repo_url: https://clarkepark.readthedocs.io/

nav:
    - Instalación: index.md
    - Ejemplo práctico : clarkepark.md
    - Referencias: references.md
    - Versión : version.md

  

theme: readthedocs



markdown_extensions:
    - smarty
    
version: 0.1.4
    
plugins:
    - search:
        min_search_length: 2
        separator: '[\s\-\.]+'
